dist: trusty
addons:
  chrome: stable

language: php

php:
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - nvm install stable
  - nvm use stable
  - npm install -g puppeteer
  - ./Tests/server/start_server.sh
  - sleep 5 # give server some time to start
  - travis_retry composer install

script:
  - vendor/bin/phpunit
